### ISSUE TITLE
branchif

### ISSUE THREAD

**Issue by tomstuart** [kddnewton/yarv#23]

**Comment by tomstuart** [comment]
This turned out to be a bit tricky because an `if` compiles to a `branchunless`, not a `branchif`. So we’re starting with #52 instead and coming back to this later.

**Comment by wildmaples** [comment]
Now that #52 is done, I think implementing this would be relatively straightforward. The only problem is thinking about the simplest test case. `branchif` is used in while-else loops that compiles to a larger set of instructions, that may not have been implemented, which is why we've previously avoided it.

**Comment by wildmaples** [comment]
Question: 

```
irb(main):003:0> puts RubyVM::InstructionSequence.compile("while 2+3; puts 'hi'; end").disasm
== disasm: #<ISeq:<compiled>@<compiled>:1 (1,0)-(1,25)> (catch: FALSE)
0000 jump                                   12                        (   1)[Li]
0002 putnil
0003 pop
0004 jump                                   12
0006 putself
0007 putstring                              "hi"
0009 opt_send_without_block                 <calldata!mid:puts, argc:1, FCALL|ARGS_SIMPLE>
0011 pop
0012 putobject                              2
0014 putobject                              3
0016 opt_plus                               <calldata!mid:+, argc:1, ARGS_SIMPLE>[CcCr]
0018 branchif                               6
0020 putnil
0021 leave
```

What does the instructions `0002 put nil` to `0004 jump 12` do? Unless I'm misunderstanding, those instructions don't get executed according to the jumps in this sequence of instructions.

**Comment by kddnewton** [comment]
Yeah they're not going to be executed. I'd assume that's supposed to be there for the return value of `while`, in case someone is assigning something like `foo = while bar; 1; end`.

**Comment by kddnewton** [comment]
That's a good case for a contribution to ruby/ruby honestly, those instructions don't need to be compiled in.

**Comment by tomstuart** [comment]
> The only problem is thinking about the simplest test case. `branchif` is used in while-else loops that compiles to a larger set of instructions, that may not have been implemented, which is why we've previously avoided it.

As Kevin told us on Slack:

> So I was messing with something completely unrelated and realized that are some options on `RubyVM::InstructionSequence` that you can pass to tell it how to compile. Turns out `peephole_optimization: false` turns off the `branchunless` stuff when you’re compiling.

Is it possible for us to make a simpler test case for `branchif` by passing `peephole_optimization: false` during compilation?

**Comment by wildmaples** [comment]
https://bugs.ruby-lang.org/issues/18801
