### ISSUE TITLE
Implement stack manipulation instructions

### ISSUE THREAD

**Issue by kddnewton** [kddnewton/yarv#7]
These instructions manipulate the stack in some way, e.g. resizing the stack or moving the stack pointer.

* [x] #171
* [x] #37
* [x] #167
* [x] #172
* [x] #47
* [x] `setn` done in #126
* [x] #89
* [x] #128

**Comment by janogonzalez** [comment]
@kddnewton I've changed `nop` for `reput` in the list

**Comment by tachyons** [comment]
I've added basic implementation of setn for https://github.com/kddnewton/yarv/pull/126
